FROM node:12

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

RUN cd frontend
RUN npm install
RUN npm run build
RUN cd ..
RUN npm install
RUN npm run build
          

# Expose port 3001
EXPOSE 3001

# Run the App
CMD [ "npm", "start" ]
