# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  #push:
  #  branches: 
  #    - "**"
  pull_request:
    branches: 
      - dev
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_backend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/backend/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/package-lock.json') }}
      - name: Install npm
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          cd backend
          npm install
      - name: Build
        run: |
          cd backend
          npm run build

  build_frontend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/backend/frontend/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/frontend/package-lock.json') }}
      - name: Install npm
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          cd backend/frontend
          npm install
      - name: Build
        run: |
          cd backend/frontend
          npm run build         
          
  linter_frontend:
    runs-on: self-hosted
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/backend/frontend/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/frontend/package-lock.json') }}
      - name: run linter
        run: |
          cd backend/frontend
          npm run lint
        

  linter_backend:
    runs-on: self-hosted
    needs: [build_backend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/backend/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/package-lock.json') }}
      - name: run linter
        run: |
          cd backend
          npm run lint

  audit_frontend:
    runs-on: self-hosted
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: audit frontend 
        run: |
          cd backend/frontend
          npm audit --audit-level=high

  audit_backend:
    runs-on: self-hosted
    needs: [build_backend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: audit backend
        run: |
          cd backend
          npm audit --audit-level=high

  test_frontend:
    runs-on: self-hosted
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/backend/frontend/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/frontend/package-lock.json') }}
      - name: run test
        run: |
          cd backend/frontend
          npm run test

  test_backend:
    runs-on: self-hosted
    needs: [build_backend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/backend/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/package-lock.json') }}
      - name: run test
        run: |
          cd backend
          npm run test
